Added SMS functionality. Long and short messages enabled.
aauxilio/Auxilio pull request #3
Opened 2018-08-28 05:34 UTC by dariomolina93

We can now send long sms via the app. No longer restricted by the 160 char limit.  Currently working on app permissions, trying to catch all edge cases.

2018-09-02 19:34 UTC, J0S349 commented
Hey @dariomolina93 , I am review this right now. I see that you commit some files from .idea folder. Can you remove those since we don't need them in the app. Thank you!

2018-09-02 20:26 UTC, J0S349 commented
I would also like if you could improve the error messages that are being displayed for debugging/logging purposes. The errors messages are see are not to helpful for resolving the issue. We can talk more about it later in the future.

2018-09-06 04:33 UTC, dariomolina93 commented
@J0S349 Yeah no problem, I'll remove the .idea folder.  What issue are you talking about? I don't have an issue present and I'm not using any debug/logger messages.

2018-09-06 06:22 UTC, J0S349 commented
@dariomolina93 So there is an issue when I try to view the PDF document that is created when a user clicks on the Affidavit button. I am working on determine whether this is an issue that your code cause or it was existing. 

Regarding the debug/logging, it would be great if you could implement that as that is something that the project we didn't setup, but would like to take that route going down the future.

2018-09-06 06:42 UTC, J0S349 commented
So did a bit more research and testing of different Android versions, mainly between Android 8.1.0 (Oreo) and Android 9 (Pie). It seems the issue that I reported is not affected by your code changes, but is another issue that we will have to address as well. So just do the mentioned code changes and I will approve your PR.

Sorry about the confusion :)

2018-11-01 04:25 UTC, dariomolina93 commented
@J0S349 @benitosanchez Updated pull request.  Took care of the comments. Check it out and if good to go merge please.

2018-11-06 15:11 UTC, J0S349 requested changes
Once you removed the files and removed the WIP label, I can review it again and merge it! Thank you Dario!!!

2018-11-06 15:11 UTC, J0S349 commented on auxilio/.idea/codeStyles/Project.xml
> +<component name="ProjectCodeStyleConfiguration">
Can you remove files located under the .idea folder as they are specific to your IDE. Once removed, it will be good to merge!

2018-11-10 05:08 UTC, dariomolina93 commented
@J0S349 The .idea directory has been removed. Thanks!

2018-11-10 19:19 UTC, merged